name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: input
    id: os-version
    attributes:
      label: Operating System Version
      description: What Operation System version(s) does this happen on?
      placeholder: "[ex: MacOS Monterey 12.6.3, MacOS Ventura 13.2, Ubuntu 22.04.1, Windows 10 22H2, Windows 11 22H2, ...]"
    validations:
      required: true
  - type: input
    id: cpu
    attributes:
      label: CPU
      description: CPU of your system
  - type: input
    id: gpu
    attributes:
      label: GPU
      description: GPU of your system
  - type: input
    id: ndi-devices
    attributes:
      label: NDI Devices
      description: Relevant NDI devices (cameras, etc)
  - type: input
    id: obs-version
    attributes:
      label: OBS Version
      description: What OBS version(s) does this happen on?
      placeholder: "[ex: 27.2.4, 28.0, 29.0.2]"
    validations:
      required: true
  - type: input
    id: obs-install
    attributes:
      label: OBS Installation Method
      description: How did you install OBS?
      placeholder: "[ex: .exe, .dep, apt, brew, PPA, Flatpak, Snap, winget, ...]"
    validations:
      required: true
  - type: input
    id: obsndi-version
    attributes:
      label: OBS-NDI Version
      description: "What version(s) of OBS-NDI does this happen on? OBS menu: `Tools`->`NDI Output Settings`, Title: `OBS-NDI ...`"
      placeholder: "[ex: 4.14.0]"
    validations:
      required: true
  - type: input
    id: obsndi-install
    attributes:
      label: OBS-NDI Installation Method
      description: How did you install OBS-NDI?
      placeholder: "[ex: .exe, .dep, apt, brew, PPA, Flatpak, Snap, winget, ...]"
    validations:
      required: true
  - type: markdown
    id: install-steps
    attributes:
      label: [Extra] Installation Steps
      description: Any noteworthy [extra] installation steps that you performed.
  - type: input
    id: obs-log
    attributes:
      label: OBS Log [URL]
      description: "In OBS' menu: `Help`->`Log Files`->`Upload Current Log File`. Click `Copy URL` and paste the link here. Or you could just paste the whole log here."
      placeholder: "[ex: https://obsproject.com/logs/xp0aosczLhVjs...]"
  - type: input
    id: ndi-version
    attributes:
      label: NDI Version
      description: "What version(s) of NDI does this happen on? OBS menu: `Tools`->`NDI Output Settings`, `NDI SDK ...`"
      placeholder: "[ex: 4.x, 5.5.3.0]"
    validations:
      required: true
  - type: markdown
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: markdown
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: What are the steps to reliably reproduce this error?
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ...
        4. See error
  - type: markdown
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: markdown
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, paste screenshots here to help explain your problem.
  - type: markdown
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
