/******************************************************************************
	Copyright (C) 2016-2026 DistroAV <contact@distroav.org>

	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program; if not, see <https://www.gnu.org/licenses/>.
******************************************************************************/

#include "ndi-receiver-report.h"
#include "plugin-main.h" // provides extern ndiLib and network_monitor

#include <algorithm>
#include <vector>
#include <sstream>
#include <iomanip>
#include <cmath>
#include <cstdlib>

// Any single-sample A/V drift beyond this is almost certainly bogus (real A/V sync
// issues are milliseconds, not seconds) and gets logged regardless of sample count.
static constexpr int64_t kSuspiciousDriftNs = 1'000'000'000; // 1 second
// Always log the first several samples after a (re)connect, since that's when a
// leftover/mismatched timestamp is most likely to slip in.
static constexpr double kLogEarlySampleCount = 10.0;
// Minimum real-time span (seconds, since the first post-reset drift sample) the drift
// regression must cover before av_drift_ns_per_hour is considered trustworthy enough
// to display; see NDIReceiverStats::av_drift_ready.
static constexpr double kMinDriftSampleSpanSeconds = 5.0;

static int64_t signed_delta(uint64_t current, uint64_t previous)
{
	if (current >= previous) {
		uint64_t d = current - previous;
		return d > static_cast<uint64_t>(INT64_MAX) ? INT64_MAX : static_cast<int64_t>(d);
	}
	uint64_t d = previous - current;
	return d > static_cast<uint64_t>(INT64_MAX) ? INT64_MIN : -static_cast<int64_t>(d);
}

static int64_t projected_relation(uint64_t a_ts_ns, uint64_t a_wall_ns, uint64_t b_ts_ns, uint64_t b_wall_ns)
{
	if (!a_ts_ns || !a_wall_ns || !b_ts_ns || !b_wall_ns)
		return 0;
	return signed_delta(a_ts_ns, b_ts_ns) + signed_delta(b_wall_ns, a_wall_ns);
}

// NDI frame timestamps are a 100-nanosecond count generated by the sending
// side's SDK. Besides the explicit NDIlib_recv_timestamp_undefined sentinel,
// a frame can occasionally carry a zero/default timestamp (e.g. right after
// a receiver is (re)created) that isn't the sentinel but also isn't a real
// value. Feeding one of those into frame-interval or A/V-drift math produces
// a huge bogus delta - e.g. drift ms/hr that starts around -1,000,000 and
// only "settles down" once enough real samples outweigh it.
static bool is_valid_ndi_timestamp(int64_t ndi_timestamp_100ns)
{
	return ndi_timestamp_100ns != NDIlib_recv_timestamp_undefined && ndi_timestamp_100ns != 0;
}

// Constructor
ReceiverInfo::ReceiverInfo(obs_source_t *ndi_source)
	: m_source(ndi_source),
	  m_receiver(nullptr),
	  ndi_name(""),
	  snapshot(),
	  running()
{
}

// ChangeNotifier registration
void ReceiverInfo::registerChangeNotifier(ChangeNotifier *notifier, const std::string &key)
{
	std::lock_guard<std::mutex> lock(m_mutex);
	if (!notifier || key.empty())
		return;
	changeNotifiers[key] = notifier;
}

void ReceiverInfo::unregisterChangeNotifier(ChangeNotifier *notifier, const std::string &key)
{
	std::lock_guard<std::mutex> lock(m_mutex);
	auto it = changeNotifiers.find(key);
	if (it == changeNotifiers.end())
		return;
	if (notifier == nullptr || it->second == notifier) {
		changeNotifiers.erase(it);
	}
}

void ReceiverInfo::notify_change()
{
	// Copy notifiers under lock, then emit outside lock.
	std::vector<ChangeNotifier *> notifiers;
	{
		std::lock_guard<std::mutex> lock(m_mutex);
		notifiers.reserve(changeNotifiers.size());
		for (auto &p : changeNotifiers)
			notifiers.push_back(p.second);
	}
	for (auto *n : notifiers) {
		if (n)
			n->emitChanged();
	}
}

// NDI name helpers
void ReceiverInfo::set_ndi_name(const std::string &name)
{
	std::lock_guard<std::mutex> lock(m_mutex);
	ndi_name = name;
}

std::string ReceiverInfo::get_ndi_name() const
{
	std::lock_guard<std::mutex> lock(m_mutex);
	return ndi_name;
}

// Snapshot accessor
NDIReceiverStats ReceiverInfo::getReportSnapshot() const
{
	std::lock_guard<std::mutex> lock(m_mutex);
	return snapshot;
}

void ReceiverInfo::reset_stats_locked()
{
	running = NDIReceiverStats();
	snapshot = NDIReceiverStats();

	last_video_ts_ns_ = 0;
	last_video_wall_ns_ = 0;
	last_audio_ts_ns_ = 0;
	last_audio_wall_ns_ = 0;
	have_av_drift_ = false;
	reg_n_ = 0.0;
	reg_sum_x_ = 0.0;
	reg_sum_y_ = 0.0;
	reg_sum_xy_ = 0.0;
	reg_sum_xx_ = 0.0;
	reg_start_wall_ns_ = 0;
}

void ReceiverInfo::set_receiver(NDIlib_recv_instance_t receiver)
{
	std::lock_guard<std::mutex> lock(m_mutex);
	m_receiver = receiver;
	// Only reset stats when a new receiver is created (non-null), not when the
	// old one is torn down (null) - that way the last-known-good stats remain
	// visible during the brief teardown window instead of flashing to "Inactive".
	if (receiver != nullptr) {
		obs_log(LOG_DEBUG, "'%s' ReceiverInfo::set_receiver: new receiver %p - resetting stats",
			obs_source_get_name(m_source), (void *)receiver);
		reset_stats_locked();
	}
}

void ReceiverInfo::log_drift_sample_locked(const char *trigger, uint64_t video_ts_ns, uint64_t video_wall_ns,
					   uint64_t audio_ts_ns, uint64_t audio_wall_ns, int64_t drift_ns) const
{
	const int64_t ts_delta = signed_delta(video_ts_ns, audio_ts_ns);
	const int64_t wall_delta = signed_delta(audio_wall_ns, video_wall_ns);
	obs_log(LOG_DEBUG,
		"'%s' AV drift sample #%.0f (triggered by %s): video_ts=%lldns video_wall=%lldns "
		"audio_ts=%lldns audio_wall=%lldns ts_delta=%lldns wall_delta=%lldns drift=%lldns "
		"drift_ns_per_hour=%.0f",
		obs_source_get_name(m_source), reg_n_, trigger, (long long)video_ts_ns, (long long)video_wall_ns,
		(long long)audio_ts_ns, (long long)audio_wall_ns, (long long)ts_delta, (long long)wall_delta,
		(long long)drift_ns, running.av_drift_ns_per_hour);
}

// Short textual status for logging/debug UI.
std::string ReceiverInfo::get_brief_receiver_status() const
{
	std::lock_guard<std::mutex> lock(m_mutex);
	if (m_receiver == nullptr) {
		return "Receiver: Not active";
	}

	std::string status = "Video: ";
	if (snapshot.osFPS > 0.0) {
		status += "Active";
		status += ", Format: " + network_monitor->getFormatDescription(snapshot.xres, snapshot.yres,
									       snapshot.frame_rate_D,
									       snapshot.frame_rate_N, snapshot.fourcc);
	} else {
		status += "Inactive";
	}

	status += ", Audio: ";
	status += (snapshot.osSPS > 0) ? "Active" : "Inactive";
	return status;
}

std::string ReceiverInfo::get_missing_receiver_status()
{
	return "Video: Inactive, Audio: Inactive";
}

void ReceiverInfo::add_drift_sample(uint64_t wall_ns, int64_t drift_ns)
{
	if (reg_n_ == 0.0)
		reg_start_wall_ns_ = wall_ns;

	// x = seconds since the first sample, y = drift in ns.
	const double x = static_cast<double>(signed_delta(wall_ns, reg_start_wall_ns_)) / 1e9;
	const double y = static_cast<double>(drift_ns);

	reg_n_ += 1.0;
	reg_sum_x_ += x;
	reg_sum_y_ += y;
	reg_sum_xy_ += x * y;
	reg_sum_xx_ += x * x;

	// Standard least-squares slope: (n?xy - ?x?y) / (n?xx - (?x)^2)
	const double denom = reg_n_ * reg_sum_xx_ - reg_sum_x_ * reg_sum_x_;
	double slope_ns_per_sec = 0.0;
	if (reg_n_ >= 2.0 && denom > 1e-9)
		slope_ns_per_sec = (reg_n_ * reg_sum_xy_ - reg_sum_x_ * reg_sum_y_) / denom;

	running.av_drift_ns_per_hour = slope_ns_per_sec * 3600.0;
	// With only a couple of samples spread over a few milliseconds, the slope above is
	// dividing near-zero by near-zero and can swing to billions of ns/hr on pure noise
	// (see log_drift_sample_locked). Don't call the regression trustworthy until it
	// spans enough real time for that noise to average out.
	running.av_drift_ready = x >= kMinDriftSampleSpanSeconds;
}

std::string format_av_drift_ms_per_hour(const NDIReceiverStats &stats)
{
	if (stats.osSPS <= 0.0)
		return "N/A";
	if (!stats.av_drift_ready)
		return "Sampling...";
	std::ostringstream out;
	out << std::fixed << std::setprecision(2) << (stats.av_drift_ns_per_hour / 1000000.0);
	return out.str();
}
// Frame callbacks
void ReceiverInfo::receive_video_frame(uint64_t t0, uint64_t t1, uint64_t t2, NDIlib_video_frame_v2_t &ndi_frame)
{
	std::lock_guard<std::mutex> lock(m_mutex);
	const bool ts_valid = is_valid_ndi_timestamp(ndi_frame.timestamp);
	if (!ts_valid) {
		obs_log(LOG_DEBUG, "'%s' receive_video_frame: rejected NDI timestamp=%lld",
			obs_source_get_name(m_source), (long long)ndi_frame.timestamp);
	}

	if (running.video_frame_count == 0) {
		running.start_video_frame_os = t1;
		if (ts_valid)
			running.start_video_frame_timestamp = (uint64_t)ndi_frame.timestamp * 100ULL;
		running.tot_frame_interval = 0;
		running.max_frame_interval = 0;
		running.fourcc = ndi_frame.FourCC;
		running.xres = ndi_frame.xres;
		running.yres = ndi_frame.yres;
		running.frame_rate_D = ndi_frame.frame_rate_D;
		running.frame_rate_N = ndi_frame.frame_rate_N;
		running.tot_video_capture = 0;
		running.max_video_capture = 0;
		running.tot_video_processing = 0;
		running.max_video_processing = 0;
	}

	// An invalid timestamp (see is_valid_ndi_timestamp) fed into the *100ULL
	// multiply (overflow) or the subsequent unsigned subtraction against a stale
	// last_video_frame_timestamp (underflow) produces a garbage frame_interval -
	// sometimes billions of times larger than a real one - which then poisons
	// max_frame_interval (and therefore jitter_ratio) for the rest of the reporting
	// window. Skip timing updates for such frames entirely, same as the A/V drift
	// tracking below already does.
	if (ts_valid) {
		const uint64_t timestamp_ns = (uint64_t)ndi_frame.timestamp * 100ULL;

		if (running.last_video_frame_timestamp != 0) {
			uint64_t frame_interval = timestamp_ns - running.last_video_frame_timestamp;
			running.tot_frame_interval += frame_interval;
			running.max_frame_interval = std::max<uint64_t>(running.max_frame_interval, frame_interval);
		}

		running.last_video_frame_timestamp = timestamp_ns;
	}

	running.target_fps = (double)ndi_frame.frame_rate_N / (double)ndi_frame.frame_rate_D;

	uint64_t capture_interval = t1 - t0;
	running.tot_video_capture += capture_interval;
	running.max_video_capture = std::max<uint64_t>(running.max_video_capture, capture_interval);

	uint64_t processing_interval = t2 - t1;
	running.tot_video_processing += processing_interval;
	running.max_video_processing = std::max<uint64_t>(running.max_video_processing, processing_interval);

	running.last_video_frame_os = t1;
	++running.video_frame_count;

	if (ts_valid) {
		const uint64_t video_ts_ns = static_cast<uint64_t>(ndi_frame.timestamp) * 100ULL;
		const uint64_t video_wall_ns = t1;

		if (last_audio_ts_ns_ && last_audio_wall_ns_) {
			const int64_t drift =
				projected_relation(video_ts_ns, video_wall_ns, last_audio_ts_ns_, last_audio_wall_ns_);
			running.av_drift_ns = drift;
			add_drift_sample(video_wall_ns, drift);
			if (reg_n_ <= kLogEarlySampleCount || std::llabs((long long)drift) > kSuspiciousDriftNs) {
				log_drift_sample_locked("video frame", video_ts_ns, video_wall_ns, last_audio_ts_ns_,
							last_audio_wall_ns_, drift);
			}
			if (!have_av_drift_) {
				running.av_drift_min_ns = drift;
				running.av_drift_max_ns = drift;
				have_av_drift_ = true;
			} else {
				running.av_drift_min_ns = std::min<int64_t>(running.av_drift_min_ns, drift);
				running.av_drift_max_ns = std::max<int64_t>(running.av_drift_max_ns, drift);
			}
		}
		last_video_ts_ns_ = video_ts_ns;
		last_video_wall_ns_ = video_wall_ns;
	}
}

void ReceiverInfo::receive_audio_frame(uint64_t t0, uint64_t t1, uint64_t, NDIlib_audio_frame_v3_t &ndi_frame)
{
	// receive_video_frame() and receive_audio_frame() are both only ever called from
	// the single NDI source thread, so they never race each other - but calculate_stats()
	// (on the network-monitor thread) locks m_mutex to snapshot `running`, and without
	// this lock that snapshot could tear mid-update against the writes below (e.g. the
	// drift regression accumulators in add_drift_sample()), which can itself produce a
	// bogus, wildly-out-of-range drift value.
	std::lock_guard<std::mutex> lock(m_mutex);
	const bool ts_valid = is_valid_ndi_timestamp(ndi_frame.timestamp);
	if (!ts_valid) {
		obs_log(LOG_DEBUG, "'%s' receive_audio_frame: rejected NDI timestamp=%lld",
			obs_source_get_name(m_source), (long long)ndi_frame.timestamp);
	}

	// See the matching guard in receive_video_frame(): an invalid timestamp
	// (see is_valid_ndi_timestamp) must not be multiplied/subtracted as if it
	// were a real timestamp, or tsSPS ends up computed from a garbage elapsed-time
	// value.
	if (ts_valid) {
		const uint64_t timestamp_ns = (uint64_t)ndi_frame.timestamp * 100ULL;
		if (running.audio_sample_count == 0)
			running.start_audio_sample_timestamp = timestamp_ns;
		running.last_audio_sample_timestamp = timestamp_ns;
	}
	if (running.audio_sample_count == 0)
		running.start_audio_sample_os = t0;
	running.last_audio_sample_os = t0;
	running.target_sps = (double)ndi_frame.sample_rate;
	running.audio_sample_count += ndi_frame.no_samples;

	if (ts_valid) {
		const uint64_t audio_ts_ns = static_cast<uint64_t>(ndi_frame.timestamp) * 100ULL;
		const uint64_t audio_wall_ns = t1;

		if (last_video_ts_ns_ && last_video_wall_ns_) {
			const int64_t drift =
				projected_relation(last_video_ts_ns_, last_video_wall_ns_, audio_ts_ns, audio_wall_ns);
			running.av_drift_ns = drift;
			add_drift_sample(audio_wall_ns, drift);
			if (reg_n_ <= kLogEarlySampleCount || std::llabs((long long)drift) > kSuspiciousDriftNs) {
				log_drift_sample_locked("audio frame", last_video_ts_ns_, last_video_wall_ns_,
							audio_ts_ns, audio_wall_ns, drift);
			}
			if (!have_av_drift_) {
				running.av_drift_min_ns = drift;
				running.av_drift_max_ns = drift;
				have_av_drift_ = true;
			} else {
				running.av_drift_min_ns = std::min<int64_t>(running.av_drift_min_ns, drift);
				running.av_drift_max_ns = std::max<int64_t>(running.av_drift_max_ns, drift);
			}
		}
		last_audio_ts_ns_ = audio_ts_ns;
		last_audio_wall_ns_ = audio_wall_ns;
	}
}

// Calculate stats and update snapshot
void ReceiverInfo::calculate_stats()
{
	{
		std::lock_guard<std::mutex> lock(m_mutex);
		snapshot = running;            // Copy running stats to snapshot for reporting
		running.video_frame_count = 0; // Reset running frame count after snapshot
		running.audio_sample_count = 0;
	}

	snapshot.osFPS = 0.0;
	snapshot.tsFPS = 0.0;
	if (snapshot.video_frame_count > 0) {
		double elapsedSeconds = (double)(snapshot.last_video_frame_os - snapshot.start_video_frame_os) / 1e9;
		if (elapsedSeconds > 0.0) {
			double dfps = (double)snapshot.video_frame_count / elapsedSeconds;
			snapshot.osFPS = dfps;
		}

		elapsedSeconds =
			(double)(snapshot.last_video_frame_timestamp - snapshot.start_video_frame_timestamp) / 1e9;
		if (elapsedSeconds > 0.0) {
			double dfps = (double)snapshot.video_frame_count / elapsedSeconds;
			snapshot.tsFPS = dfps;
		}
		snapshot.avg_frame_interval =
			snapshot.video_frame_count > 0 ? snapshot.tot_frame_interval / snapshot.video_frame_count : 0;
		snapshot.avg_video_capture =
			snapshot.video_frame_count > 0 ? snapshot.tot_video_capture / snapshot.video_frame_count : 0;
		snapshot.avg_video_processing =
			snapshot.video_frame_count > 0 ? snapshot.tot_video_processing / snapshot.video_frame_count : 0;
	}

	if (snapshot.audio_sample_count > 0) {
		double elapsedSeconds = (double)(snapshot.last_audio_sample_os - snapshot.start_audio_sample_os) / 1e9;
		if (elapsedSeconds > 0.0) {
			double dsps = (double)snapshot.audio_sample_count / elapsedSeconds;
			snapshot.osSPS = dsps;
		}
		elapsedSeconds =
			(double)(snapshot.last_audio_sample_timestamp - snapshot.start_audio_sample_timestamp) / 1e9;
		if (elapsedSeconds > 0.0) {
			double dsps = (double)snapshot.audio_sample_count / elapsedSeconds;
			snapshot.tsSPS = dsps;
		}
	}

	snapshot.deficit_fps = 0.0;
	snapshot.budget_used_per_frame_capture = 0.0;
	snapshot.budget_used_per_frame_processing = 0.0;
	snapshot.max_capture_pct = 0.0;
	snapshot.max_process_pct = 0.0;
	if (snapshot.target_fps > 0) {
		snapshot.deficit_fps = ((snapshot.target_fps - snapshot.osFPS) / snapshot.target_fps);
		snapshot.budget_used_per_frame_capture = snapshot.avg_video_capture / (1e9 / snapshot.target_fps);
		snapshot.budget_used_per_frame_processing = snapshot.avg_video_processing / (1e9 / snapshot.target_fps);

		// Worst-case capture/processing time as a fraction of the target frame period
		// (not divided by the average - so a max that equals one full frame period at
		// the target fps always reads as 100%, regardless of how small the average is).
		snapshot.max_capture_pct = (double)snapshot.max_video_capture / (1e9 / snapshot.target_fps);
		snapshot.max_process_pct = (double)snapshot.max_video_processing / (1e9 / snapshot.target_fps);
	}

	snapshot.deficit_sps = 0.0;
	if (snapshot.target_sps > 0)
		snapshot.deficit_sps = ((snapshot.target_sps - snapshot.osSPS) / snapshot.target_sps);

	snapshot.jitter_ratio = 0.0;
	if (snapshot.avg_frame_interval > 0)
		snapshot.jitter_ratio =
			(double)snapshot.max_frame_interval /
			(double)snapshot.avg_frame_interval; // TODO: reset max_frame_interval periodically?

	snapshot.format_description = network_monitor->getFormatDescription(
		snapshot.xres, snapshot.yres, snapshot.frame_rate_D, snapshot.frame_rate_N, snapshot.fourcc);

	// Query NDI SDK for performance & queue info (if available)
	{
		std::lock_guard<std::mutex> lock(m_mutex);
		if (ndiLib && m_receiver != nullptr) {

			NDIlib_recv_performance_t total, dropped;
			ndiLib->recv_get_performance(m_receiver, &total, &dropped);
			snapshot.video_frames_dropped = dropped.video_frames;
			snapshot.audio_samples_dropped = dropped.audio_frames;

			NDIlib_recv_queue_t queue;
			ndiLib->recv_get_queue(m_receiver, &queue);
			snapshot.video_queue_size = queue.video_frames;
			snapshot.audio_queue_size = queue.audio_frames;
		}

		snapshot.format_description = network_monitor->getFormatDescription(
			snapshot.xres, snapshot.yres, snapshot.frame_rate_D, snapshot.frame_rate_N, snapshot.fourcc);

		snapshot.obs_source_name = obs_source_get_name(m_source);
	}
	// connections/discoverable are set by network-monitor elsewhere; we don't call it here
	// to avoid header cycles. If needed, network_monitor usage should occur in another translation unit.
}
