name: Check Code Formatting 🛠️
on:
  workflow_call:
jobs:
  clang-format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: clang-format check 🐉
        id: clang-format
        uses: ./.github/actions/run-clang-format
        with:
          failCondition: error

  gersemi:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: gersemi Check 🎛️
        id: gersemi
        uses: ./.github/actions/run-gersemi
        with:
          failCondition: error
